[package]
name = "bloom-filter"
version = "0.1.0"
authors = ["Iiro Sulopuisto <iisulop@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fasthash = "0.3"
bit-vec = "0.6.2"
